# -*- mode: ruby -*-
# vi:set ft=ruby

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    config.ssh.insert_key = false
    config.vm.provider :virtualbox do |vb|
        vb.customize ["modifyvm", :id, "--memory", "256"]
    end

    # Application server 1.
    config.vm.define "tmp1" do |app|
        app.vm.hostname = "master"
        app.vm.box = "centos7"
        app.vm.network :private_network, ip: "192.168.60.7"
    end

     # Application server 2.
    config.vm.define "tmp2" do |app|
        app.vm.hostname = "node1"
        app.vm.box = "centos7"
        app.vm.network :private_network, ip: "192.168.60.8"
    end

     # Database server .
    config.vm.define "tmp3" do |app|
        app.vm.hostname = "node2"
        app.vm.box = "centos7"
        app.vm.network :private_network, ip: "192.168.60.9"
    end
end
